---
# tasks file for rbenv

- name: Install dependencies
  package:
    name: "{{rbenv_packages}}"
    state: present

- name: Check out rbenv sources
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root }}"
    version: "{{ rbenv_version }}"
    accept_hostkey: true
    force: true

- name: Add rbenv initialization to system-wide profile
  template:
    src: rbenv.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: root
    group: root
    mode: 0755

- name: Create base directory for plugins
  file:
    path: "{{rbenv_plugins_root}}"
    state: directory
    owner: root
    group: root

- include_tasks: plugin.yml
  vars:
    rbenv_plugin: "{{lookup('vars', item)}}"
  loop: "{{rbenv_plugins}}"

- name: Install rubies
  shell: "/bin/bash -lc 'rbenv install -s {{item}}'"
  args:
    creates: "{{rbenv_root}}/versions/{{item}}/bin/ruby"
  loop: "{{rbenv_rubies}}"
