---
# tasks file for rbenv

- name: Install dependencies
  package:
    name: "{{rbenv_packages}}"
    state: present

- name: Check out rbenv sources
  git:
    repo: "{{ rbenv_repo }}"
    dest: "{{ rbenv_root }}"
    version: "{{ rbenv_version }}"
    accept_hostkey: true
    force: true
    depth: 1
  become: true
  become_user: "{{rbenv_user}}"

- name: Setup rbenv for system
  template:
    src: rbenv.sh.j2
    dest: /etc/profile.d/rbenv.sh
    mode: 0755
  become: true
  when: rbenv_user == 'root'

- name: Setup rbenv for user
  blockinfile:
    path: "{{rbenv_user_home}}/.profile"
    block: |
      # rbenv setup
      if [ -f {{rbenv_root}}/bin/rbenv ]; then
        export PATH={{rbenv_root}}/bin/:$PATH
        eval "$({{rbenv_root}}/bin/rbenv init -)"
      fi
    create: true
    owner: "{{rbenv_user}}"
    group: "{{rbenv_group}}"
  when: rbenv_user != 'root'

- name: Create base directory for plugins
  file:
    path: "{{rbenv_plugins_root}}"
    state: directory
    owner: "{{rbenv_user}}"
    group: "{{rbenv_group}}"

- include_tasks: plugin.yml
  vars:
    rbenv_plugin: "{{lookup('vars', item)}}"
  loop: "{{rbenv_plugins}}"

- name: Tweak library files to match jruby requirements
  file:
    path: "/usr/lib/libcrypt.so.1"
    src: "/usr/lib/libcrypto.so.1.0.0"
    state: link
  when: >
    ansible_os_family == 'Alpine' and
    rbenv_rubies | map('truncate', 5, True, '') | select('eq', 'jruby') | list | count | int
  tags: rubies_install

- name: Install rubies
  command: "/bin/bash -lc 'rbenv install -s {{item}}'"
  args:
    creates: "{{rbenv_root}}/versions/{{item}}/bin/ruby"
  loop: "{{rbenv_rubies}}"
  become: true
  become_user: "{{rbenv_user}}"
  tags: rubies_install
