---
# Ansible tasks to install a rbenv plugin

- name: Install plugin dependencies
  package:
    name: "{{ rbenv_plugin.packages[ansible_os_family] }}"
    state: present
  when: rbenv_plugin.packages is defined

- name: Check out plugin sources
  git:
    repo: "{{ rbenv_plugin.repo }}"
    dest: "{{ rbenv_plugins_root }}/{{ rbenv_plugin.name }}"
    version: "{{ rbenv_plugin.version }}"
    accept_hostkey: true
    force: true
  become: true
  become_user: "{{rbenv_user}}"
