---
- name: Prepare
  hosts: all

  tasks:

    - name: Add missing package for `useradd`
      package:
        name: shadow
        state: present
      when: ansible_os_family == 'Alpine'

    - name: Create user for testing
      user: name=bithium

    - name: Setup local package cache
      file:
        src: /var/cache/apk
        dest: /etc/apk/cache
        state: link
      when: ansible_os_family == 'Alpine'

    - name: Setup image for keeping downloaded packages
      file:
        path: /etc/apt/apt.conf.d/docker-clean
        state: absent
      when: ansible_os_family == 'Debian'
