---
- name: Converge
  hosts: all
  vars:
    rbenv_version: v1.1.1
    rbenv_rubies:
      - 2.5.1
      - jruby-9.1.17.0
  vars_files:
    - goss.yml

  pre_tasks:
    - name: Install packages for building test rubies
      package:
        name: "{{item}}"
        state: present
      with_items:
        - default-jdk

  roles:
    - role: rbenv

  tasks:
    - name: Dump host variables for role
      template: src=config.yml.j2 dest={{goss_test_variables}}
