---
- name: Converge
  hosts: all
  vars:
    packages:
      Alpine:
        - openjdk8-jre
      Debian:
        - default-jre
    rbenv_version: v1.1.1
    rbenv_rubies:
      - 2.5.1
      - jruby-9.1.17.0
  vars_files:
    - goss.yml

  pre_tasks:
    - name: Install packages for building test rubies
      package:
        name: "{{packages[ansible_os_family]}}"
        state: present

  roles:
    - role: rbenv

  tasks:
    - name: Dump host variables for role
      template: src=config.yml.j2 dest={{goss_test_variables}}
