---
dependency:
  name: galaxy
driver:
  name: podman
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: rbenv-alpine-3.11
    image: alpine:3.11
    volumes:
      - "/mnt/mirrors/alpine/3.11:/var/cache/apk"
  - name: rbenv-alpine-3.12
    image: alpine:3.12
    volumes:
      - "/mnt/mirrors/alpine/3.12:/var/cache/apk"
  - name: rbenv-debian-stable
    image: debian:stable
    volumes:
      - "/mnt/mirrors/debian/stable:/var/cache/apt/archives"
    command: sleep infinity
  - name: rbenv-ubuntu-18.04
    image: ubuntu:18.04
    volumes:
      - "/mnt/mirrors/ubuntu/18.04:/var/cache/apt/archives"
    command: sleep infinity
  - name: rbenv-ubuntu-20.04
    image: ubuntu:20.04
    volumes:
      - "/mnt/mirrors/ubuntu/20.04:/var/cache/apt/archives"
    command: sleep infinity
provisioner:
  name: ansible
  # log: true
  config_options:
    defaults:
      interpreter_python: "/usr/bin/python3"
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/playbook.yml
    verify: ../common/verify.yml
  lint: |
    set -e
    yamllint .
    ansible-lint
    flake8
  env:
    RBENV_USER: "bithium"
scenario:
  name: user
